########################################
debug: true
server:
  port: 8888
# spring
spring:
  profiles:
    active: dev
  application:
    name: easy-mybatis-test
# log
logging:
  level:
    root: info
    org.springframework.data: debug
    com.nuochen: debug
  file:
    path: logs
    name: ${spring.application.name}.log

datasource:
  test:
    url: jdbc:mysql://rm-hp3u6q3sj8l5hxpy87m.mysql.huhehaote.rds.aliyuncs.com:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: zodiac
    password: 5ISxX7u4V#4wg*hr