########################################
debug: true
server:
  port: 8888
# spring
spring:
  profiles:
    active: dev
  application:
    name: easy-mybatis-test
# log
logging:
  level:
    root: info
    com.github.freegeese.easymybatis.test.db1.mapper: debug
  file:
    path: logs
    name: ${spring.application.name}.log

datasource:
  test:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  test2:
    url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456

easy-mybatis:
  java-case-format: lower_camel
  database-case-format: lower_underscore
